[package]
name = "stadio"
version = "0.1.0"
edition = "2024"

[dependencies]
enigo = { version = "0.6.1", features = ["wayland"] }
gilrs = "0.11.2"
iced = { version = "0.14.0", features = ["canvas", "tokio"] }
log = "0.4.33"
simple_logger = "5.2.0"
tokio = { version = "1", features = ["time"] }
x11rb = "0.14.0"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.4"
objc2-app-kit = { version = "0.3.2", default-features = false, features = ["NSApplication", "NSResponder", "NSWindow", "std"] }
